### ISSUE TITLE
Open topic to direct drive joint

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/ros_serial_bridge#17]
This code do not have topic to send or receive position/velocity/torque to motor.

We should add new topic to control single joint.

**Comment by Myzhar** [comment]
Position control requires an absolute encoder or at least an "homing" procedure with a fixed zero point.
Furthermore we need to use an encoder with "index" signal and we need to handle that signal.

**Comment by rbonghi** [comment]
yes!
The control position is a future work, but I think to add a velocity joint
topic to control a single motor.

About "homing" procedure I'm sure with your issue. :smile:

2015-04-20 21:28 GMT+02:00 Walter Lucetti <notifications@github.com>:

**Comment by rbonghi** [comment]
Solved in branch #20
