### ISSUE TITLE
New policy for velocity and odometry topic

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/ros_serial_bridge#18]
I would like to define a new policy for twist commands.

We have called a command to drive ours robots **/name_robot/command/velocity**, but I would lite to rename in: **/name_robot/cmd_vel**.
The same for Odometry topic, in **/name_robot/odom**

@Myzhar

**Comment by rbonghi** [comment]
Added another information:

rosparam with name of robot in **/info/robot**

**Comment by Myzhar** [comment]
+1

**Comment by rbonghi** [comment]
In according a new policy, now is **removed** reference of name robot in all topics, node and rosparam.

Finally now is remove rosparam **info/robot_name**
